USE [master]
GO
ALTER DATABASE [AIS_YXSP2_3] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [AIS_YXSP2_3] SET RECOVERY SIMPLE
GO
USE [AIS_YXSP2_3]
GO
DBCC SHRINKFILE (N'SCM102SP2_log' , 0,TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE [AIS_YXSP2_3] SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE [AIS_YXSP2_3] SET RECOVERY FULL
GO
 
--查询指定数据库的日志文件名称
USE [AIS_YXSP2_3] 
GO
SELECT name FROM SYS.database_files WHERE type_desc='LOG'