--批量清空批号信息

USE TEST_YXDZP2018;

SELECT FBatchNo* FROM T_ICITEM WHERE FNUMBER='2.03.0413'
SELECT FBatchNo FROM ICInvInitial WHERE FITEMID=12337
SELECT  FBatchNo FROM ICInvBal WHERE FITEMID=12337
SELECT FBatchNo FROM ICBal WHERE FITEMID=12337
SELECT FBatchNo FROM ICStockBillEntry WHERE FITEMID=12337
UPDATE icstockbillentry SET fbatchno='' WHERE FITEMID=12337
SELECT FBatchNo,* FROM ICInventory WHERE FITEMID=12337
UPDATE ICInventory SET fbatchno='' WHERE FITEMID=12337


USE TEST_YXDZP2018;

SELECT  * FROM T_ICITEM WHERE FNUMBER='3.05.9998'
SELECT FBatchNo FROM ICInvInitial WHERE FITEMID=7212
SELECT  FBatchNo FROM ICInvBal WHERE FITEMID=7212
SELECT FBatchNo FROM ICBal WHERE FITEMID=7212
SELECT FBatchNo FROM ICStockBillEntry WHERE FITEMID=7212
UPDATE icstockbillentry SET fbatchno='' WHERE FITEMID=7212
SELECT FBatchNo,* FROM ICInventory WHERE FITEMID=7212 AND fbatchno='20200303'
DELETE FROM ICInventory WHERE FITEMID=7212 AND fbatchno='20200303'
UPDATE ICInventory SET fqty=1 WHERE FITEMID=7212 


SELECT * FROM icinventory  WHERE fbatchno='' order BY fitemid 

