集团
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND G.FNUMBER >='09.0014'  AND G.FNUMBER <='09.0014' @","0","D","肉业")

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND G.FNUMBER >='01.0751'  AND G.FNUMBER <='01.0751' @","0","D","食品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND G.FNUMBER >='08.01.005'  AND G.FNUMBER <='08.01.005' @","0","D","肉制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND G.FNUMBER >='05.03.0009'  AND G.FNUMBER <='05.03.0009' @","0","D","豆制品")



肉业
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND G.FNUMBER >='01.0092.01'  AND G.FNUMBER <='01.0092.03' @","0","D","食品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='08.01.001'  OR G.FNUMBER ='08.01.017') @","0","D","肉制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='05.03.0007'  OR G.FNUMBER ='05.03.0004') @","0","D","豆制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='02.901'  OR G.FNUMBER ='02.901') @","0","D","油脂")



食品
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='09.0004.999'  OR G.FNUMBER ='09.0004.999') @","0","D","肉业")


=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND G.FNUMBER >='01.03.005'  AND G.FNUMBER <='01.03.030' @","0","D","肉制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND G.FNUMBER >='05.01.0001'  AND G.FNUMBER <'05.06.0001' @","0","D","豆制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='02.904'  OR G.FNUMBER ='02.904') @","0","D","油脂")


肉制品

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='10.0002'  OR G.FNUMBER ='09.0001') @","0","D","肉业")

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='01.0340'  OR G.FNUMBER ='01.0340') @","0","D","食品")

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='05.03.0003'  OR G.FNUMBER ='05.03.0003') @","0","D","豆制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='02.902'  OR G.FNUMBER ='02.902') @","0","D","油脂")

豆制品

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='10.0003'  OR G.FNUMBER ='09.0005') @","0","D","肉业")

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='01.0388'  OR G.FNUMBER ='01.0388') @","0","D","食品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='08.01.003'  OR G.FNUMBER ='08.01.003') @","0","D","肉制品")

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='02.903'  OR G.FNUMBER ='02.903') @","0","D","油脂")

油脂

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='09.0002'  OR G.FNUMBER ='09.0002') @","0","D","肉业")

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='01.0793'  OR G.FNUMBER ='01.0793') @","0","D","食品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='08.01.009'  OR G.FNUMBER ='08.01.009') @","0","D","肉制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='05.03.0002'  OR G.FNUMBER ='05.03.0002') @","0","D","豆制品")

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='002'  OR G.FNUMBER ='002') @","0","D","商贸")

商贸

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='02.912'  OR G.FNUMBER ='02.912') @","0","D","油脂")


饲料

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='09.0015'  OR G.FNUMBER ='09.0015') @","0","D","肉业")


=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='08.01.008'  OR G.FNUMBER ='08.01.008') @","0","D","肉制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='05.03.0001'  OR G.FNUMBER ='05.03.0001') @","0","D","豆制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='01.991'  OR G.FNUMBER ='01.991') @","0","D","油脂")


海灵宝
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='02.913'  OR G.FNUMBER ='02.913') @","0","D","油脂")


物流
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='08.01.014'  OR G.FNUMBER ='08.01.014') @","0","D","肉制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='05.03.0010'  OR G.FNUMBER ='05.03.0010') @","0","D","豆制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='02.914'  OR G.FNUMBER ='02.914') @","0","D","油脂")

动保
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='08.01.006'  OR G.FNUMBER ='08.01.006') @","0","D","肉制品")


厦门银翔农牧
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='09.0003'  OR G.FNUMBER ='09.0003') @","0","D","肉业")

=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='01.0803'  OR G.FNUMBER ='01.0803') @","0","D","食品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='08.01.016'  OR G.FNUMBER ='08.01.016') @","0","D","肉制品")




银祥优鲜(收入)




=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='01.0858'  OR G.FNUMBER ='01.0858') @","0","D","食品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='01.03.101'  OR G.FNUMBER ='01.03.101') @","0","D","肉制品")


国重(收入)


=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='09.0013'  OR G.FNUMBER ='09.0013') @","0","D","肉业")


=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='08.01.012'  OR G.FNUMBER ='08.01.012') @","0","D","肉制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='05.03.0011'  OR G.FNUMBER ='05.03.0011') @","0","D","豆制品")
=KPGETSQL("SELECT ISNULL(SUM(CASE WHEN v.FTranType=80 THEN y.FAmount ELSE FAMOUNTINCLUDETAX END ),0) FAMOUNTINCLUDETAX FROM DBO.ICSALE V INNER JOIN DBO.ICSALEENTRY Y  ON Y.FINTERID = V.FINTERID INNER JOIN DBO.T_ORGANIZATION G ON G.FITEMID=V.FCUSTID WHERE V.FCHECKERID>0 AND V.FCANCELLATION=0   AND V.FDATE>='<__RPTBEGINDATE__>' AND V.FDATE <='<__RPTENDDATE__>' AND ( G.FNUMBER ='02.906'  OR G.FNUMBER ='02.906') @","0","D","油脂")





